# config.yaml

paths:
  raw_data: data/raw/combined.json
  clean_data: data/clean/cleaned.json
  synthetic_data: data/synthetic/
  merged_data: data/merged/
  model_dir: models/orphgpt/

synthetic:
  use: true
  num_cases: 500
